Edit contact
jurikaca/react-app pull request #2
Opened 2023-04-24 15:09 UTC by Inisi

finished with edit contact functionality

2023-04-24 16:25 UTC, jurikaca requested changes

2023-04-24 16:25 UTC, jurikaca commented on src/components/exercises/App1/AddContact.js
> +        placeholder={isEditForm ? props.contact.name : "Enter Name"}
Do not change placeholder, you can leave same value for placeholder.

2023-04-24 16:25 UTC, jurikaca commented on src/components/exercises/App1/AddContact.js
> +        value={name}
Make value dynamic when it exists

2023-04-24 16:25 UTC, jurikaca commented on src/components/exercises/App1/AddContact.js
> +        <button onClick={addContactHandler}>Add new contact</button>
Make the logic only for text, not the whole button

2023-04-24 16:25 UTC, jurikaca commented on src/components/exercises/App1/redux/slices/contactSlice.js
> +      state.updateRequired = true;
remove this

2023-04-24 16:25 UTC, jurikaca commented on src/components/exercises/App1/redux/slices/contactSlice.js
> +      const contactId = action.payload;
- remove unnecessary variables
- use .forEach function to loop contacts
- remove console

2023-04-24 16:27 UTC, Inisi commented
Po ti paske qen i fulliqt

On Mon, 24 Apr 2023 at 18:25, jurikaca ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/exercises/App1/AddContact.js
> <https://github.com/jurikaca/react-app/pull/2#discussion_r1175519455>:
>
> >    };
>
>    return (
>      <section className="add-contact">
> -        <input type="text" placeholder={'Enter Name'} value={name} onChange={(e) => setName(e.target.value)}/>
> -        <input type="text" placeholder={'Enter Email'} value={email} onChange={(e) => setEmail(e.target.value)}/>
> +      <input
> +        type="text"
> +        placeholder={isEditForm ? props.contact.name : "Enter Name"}
>
> Do not change placeholder, you can leave same value for placeholder.
> ------------------------------
>
> In src/components/exercises/App1/AddContact.js
> <https://github.com/jurikaca/react-app/pull/2#discussion_r1175521468>:
>
> >    };
>
>    return (
>      <section className="add-contact">
> -        <input type="text" placeholder={'Enter Name'} value={name} onChange={(e) => setName(e.target.value)}/>
> -        <input type="text" placeholder={'Enter Email'} value={email} onChange={(e) => setEmail(e.target.value)}/>
> +      <input
> +        type="text"
> +        placeholder={isEditForm ? props.contact.name : "Enter Name"}
> +        value={name}
>
> Make value dynamic when it exists
> ------------------------------
>
> In src/components/exercises/App1/AddContact.js
> <https://github.com/jurikaca/react-app/pull/2#discussion_r1175521883>:
>
> >        <br />
> -      <button onClick={addContactHandler}>Add new contact</button>
> +      {!isEditForm && (
> +        <button onClick={addContactHandler}>Add new contact</button>
>
> Make the logic only for text, not the whole button
> ------------------------------
>
> In src/components/exercises/App1/redux/slices/contactSlice.js
> <https://github.com/jurikaca/react-app/pull/2#discussion_r1175523171>:
>
> > +      });
> +    },
> +    deleteContact: (state, action) => {
> +      state.data = state.data.filter(
> +        (contact) => contact.id !== action.payload.id
> +      );
> +      contactSlice.caseReducers.setDefaultSelectedContact(state);
> +    },
> +    editContact: (state, action) => {
> +      state.data.forEach((contact) => {
> +        if (contact.id === action.payload) {
> +          contact.edit = !contact.edit;
> +        }
> +      });
> +
> +      state.updateRequired = true;
>
> remove this
> ------------------------------
>
> In src/components/exercises/App1/redux/slices/contactSlice.js
> <https://github.com/jurikaca/react-app/pull/2#discussion_r1175526911>:
>
> > -        status: 'idle',
> -        data: [],
> -        selectedContact: null,
> +  name: "contact",
> +  initialState: {
> +    status: "idle",
> +    data: [],
> +    selectedContact: null,
> +    updateRequired: false,
> +  },
> +  reducers: {
> +    addContact: (state, action) => {
> +      state.data.push(action.payload);
> +    },
> +    updateContact: (state, action) => {
> +      const contactId = action.payload;
>
>
>    - remove unnecessary variables
>    - use .forEach function to loop contacts
>    - remove console
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jurikaca/react-app/pull/2#pullrequestreview-1398390780>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYRJPPEUATFRN4LU5OHM3P3XC2SQXANCNFSM6AAAAAAXJXE3AM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-26 12:01 UTC, jurikaca approved these changes

2023-04-26 12:02 UTC, merged